// ⚠️ AUTO-GENERATED by scripts/generate-env.ts — do not edit manually.
// To update values, set environment variables or edit scripts/generate-env.ts defaults.

export const env = {
  // Portfolio
  PORTFOLIO_URL: 'https://ricardo-camilo-dev-frontend-web.netlify.app/',

  // Social Links
  GITHUB_URL: 'https://github.com/ricardo-camilo-programador-frontend-web',
  LINKEDIN_URL: 'https://www.linkedin.com/in/ricardo-camilo-programador-frontend-web-developer/',
  X_URL: 'https://x.com/Ricardo50993066',
  INSTAGRAM_URL: 'https://www.instagram.com/ricardo.camilo.dev/',
  YOUTUBE_URL: 'https://www.youtube.com/@ricardocamilodev',
  FACEBOOK_URL: 'https://www.facebook.com/profile.php?id=61571852212026',

  // Freelance Platforms
  FREELAS_99_URL: 'https://www.99freelas.com.br/user/CamillusBloodfallen',
  WORKANA_URL: 'https://www.workana.com/freelancer/7a5de74a4785b737b517d8746a01cd23',

  // Support
  BUYMEACOFFEE_USERNAME: 'ricardo.camilo.frontend',
  BUYMEACOFFEE_URL: 'https://buymeacoffee.com/ricardo.camilo.frontend',

  // Design
  FIGMA_URL: 'https://www.figma.com/@riddhilimbachiy',

  // Contact
  CONTACT_EMAIL: 'ricardo.camilo.dev@gmail.com',

  // Analytics
  GA_MEASUREMENT_ID: 'G-DLRDXGG3V1',
  GTM_ID: 'GTM-5HWWCSZ4',

  // Visit Counter (counter.dev)
  COUNTER_DEV_ID: 'f30df6f3-776d-4154-959d-0210ac8a8325',
} as const;
