/**
 * Generate src/configs/env.ts from environment variables.
 *
 * This script runs as a pre-build step so that env vars set on Netlify
 * (or locally in .env) are injected into the Angular build automatically.
 *
 * Usage:
 *   npx tsx scripts/generate-env.ts        # reads process.env
 *   npx tsx scripts/generate-env.ts --local # uses hardcoded defaults for dev
 */

import { writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { resolve, dirname } from 'node:path'

const __dirname = dirname(new URL(import.meta.url).pathname)
const outFile = resolve(__dirname, '..', 'src', 'configs', 'env.ts')

// Hardcoded defaults for local development (--local flag or missing vars)
const defaults: Record<string, string> = {
  VITE_PORTFOLIO_URL: 'https://ricardo-camilo-dev-frontend-web.netlify.app/',
  VITE_GITHUB_URL: 'https://github.com/ricardo-camilo-programador-frontend-web',
  VITE_LINKEDIN_URL: 'https://www.linkedin.com/in/ricardo-camilo-programador-frontend-web-developer/',
  VITE_X_URL: 'https://x.com/Ricardo50993066',
  VITE_INSTAGRAM_URL: 'https://www.instagram.com/ricardo.camilo.dev/',
  VITE_YOUTUBE_URL: 'https://www.youtube.com/@ricardocamilodev',
  VITE_FACEBOOK_URL: 'https://www.facebook.com/profile.php?id=61571852212026',
  VITE_99FREELAS_URL: 'https://www.99freelas.com.br/user/CamillusBloodfallen',
  VITE_WORKANA_URL: 'https://www.workana.com/freelancer/7a5de74a4785b737b517d8746a01cd23',
  VITE_BUYMEACOFFEE_URL: 'https://buymeacoffee.com/ricardo.camilo.frontend',
  VITE_FIGMA_URL: 'https://www.figma.com/@riddhilimbachiy',
  VITE_CONTACT_EMAIL: 'ricardo.camilo.dev@gmail.com',
  VITE_GA_MEASUREMENT_ID: 'G-DLRDXGG3V1',
  VITE_GTM_ID: 'GTM-5HWWCSZ4',
  VITE_COUNTER_DEV_ID: 'f30df6f3-776d-4154-959d-0210ac8a8325',
}

function getEnv(key: string): string {
  return process.env[key] || defaults[key] || ''
}

function generateEnvFile(): void {
  const content = `// ⚠️ AUTO-GENERATED by scripts/generate-env.ts — do not edit manually.
// To update values, set environment variables or edit scripts/generate-env.ts defaults.

export const env = {
  // Portfolio
  PORTFOLIO_URL: '${getEnv('VITE_PORTFOLIO_URL')}',

  // Social Links
  GITHUB_URL: '${getEnv('VITE_GITHUB_URL')}',
  LINKEDIN_URL: '${getEnv('VITE_LINKEDIN_URL')}',
  X_URL: '${getEnv('VITE_X_URL')}',
  INSTAGRAM_URL: '${getEnv('VITE_INSTAGRAM_URL')}',
  YOUTUBE_URL: '${getEnv('VITE_YOUTUBE_URL')}',
  FACEBOOK_URL: '${getEnv('VITE_FACEBOOK_URL')}',

  // Freelance Platforms
  FREELAS_99_URL: '${getEnv('VITE_99FREELAS_URL')}',
  WORKANA_URL: '${getEnv('VITE_WORKANA_URL')}',

  // Support
  BUYMEACOFFEE_USERNAME: '${getEnv('VITE_BUYMEACOFFEE_URL').split('/').pop() || ''}',
  BUYMEACOFFEE_URL: '${getEnv('VITE_BUYMEACOFFEE_URL')}',

  // Design
  FIGMA_URL: '${getEnv('VITE_FIGMA_URL')}',

  // Contact
  CONTACT_EMAIL: '${getEnv('VITE_CONTACT_EMAIL')}',

  // Analytics
  GA_MEASUREMENT_ID: '${getEnv('VITE_GA_MEASUREMENT_ID')}',
  GTM_ID: '${getEnv('VITE_GTM_ID')}',

  // Visit Counter (counter.dev)
  COUNTER_DEV_ID: '${getEnv('VITE_COUNTER_DEV_ID')}',
} as const;
`

  const dir = dirname(outFile)
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true })
  }

  writeFileSync(outFile, content, 'utf-8')
  console.log(`✅ Generated ${outFile}`)
}

generateEnvFile()
